name: tests

on:
  push:
  pull_request:

jobs:
  tox:
    name: ${{ matrix.platform.name }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: py38
            python-version: "3.8"
          - name: py39
            python-version: "3.9"
          - name: py310
            python-version: "3.10"
          - name: py311
            python-version: "3.11"
          - name: py312
            python-version: "3.12"
          # TODO(vytas): Enable when Falcon stable supports 3.13.
          # - name: py313
          #   python-version: "3.13.0-rc.1 - 3.13"
          - name: pypy
            python-version: "pypy-3.10"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.platform.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox

      - name: Run tox
        run: tox
